# Usecase: TabEval models for classification tasks

## Step 1: Prepare environment

- Set up the runtime

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import os
import sys

project_dir = os.getcwd()
while not os.path.exists(os.path.join(project_dir, ".git")):
    project_dir = os.path.dirname(project_dir)
print(f"Project directory: {project_dir}")
sys.path.insert(0, project_dir)

Project directory: /home/xj265/phd/codebase/Euphratica/Euphratica-dev

- Import customised libraries

In [ ]:
import numpy as np
import pandas as pd
from tabeval.plugins import Plugins
from tabcamel.data.dataset import TabularDataset

## Step 2: Specify the results of interest

* Generate the data with known causal structure

In [4]:
dataset = TabularDataset(
    dataset_name="statlog_german_credit_data",
    task_type="classification"
)
X = dataset.X_df
y = dataset.y_s
X.shape, y.shape

((1000, 20), (1000,))

## Step 3: Export results

* Fit the model

In [5]:
model = Plugins().get("arf")
model.fit(dataset.data_df)

Initial accuracy is 0.7215
Iteration number 1 reached accuracy of 0.469.

In [6]:
model.generate(100)

,Attribute1,Attribute2,Attribute3,Attribute4,Attribute5,Attribute6,Attribute7,Attribute8,Attribute9,Attribute10,...,Attribute12,Attribute13,Attribute14,Attribute15,Attribute16,Attribute17,Attribute18,Attribute19,Attribute20,target
0,A12,23,A31,A46,1154,A61,A71,4,A93,A101,...,A122,48,A143,A153,2,A172,1,A191,A201,2
1,A11,18,A34,A41,6121,A64,A71,2,A91,A101,...,A122,42,A143,A152,1,A173,1,A192,A201,1
2,A12,48,A33,A49,15270,A61,A71,2,A93,A101,...,A123,50,A143,A152,1,A171,1,A192,A201,1
3,A12,5,A32,A43,638,A61,A73,3,A93,A103,...,A121,48,A143,A152,1,A173,1,A191,A201,1
4,A11,7,A32,A49,889,A61,A73,4,A91,A101,...,A122,23,A143,A152,1,A173,1,A191,A201,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,A11,31,A32,A40,1786,A61,A72,2,A92,A102,...,A122,23,A143,A152,1,A173,1,A191,A201,1
96,A14,28,A34,A40,3504,A65,A75,4,A92,A101,...,A123,55,A143,A152,1,A172,1,A191,A201,1
97,A14,13,A34,A42,2053,A61,A73,2,A92,A101,...,A123,32,A143,A152,1,A173,1,A191,A201,1
98,A12,19,A32,A41,10204,A63,A71,4,A93,A101,...,A124,38,A143,A153,1,A174,1,A192,A201,1
99,A14,9,A32,A43,2911,A61,A75,4,A93,A101,...,A121,36,A141,A152,2,A173,1,A191,A201,1